import { type Transaction } from './types';
import { subDays } from 'date-fns';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: subDays(new Date(), 1).toISOString(),
    description: 'Monthly Salary',
    amount: 5000,
    type: 'income',
    category: 'Savings',
  },
  {
    id: '2',
    date: subDays(new Date(), 2).toISOString(),
    description: 'Rent Payment',
    amount: 1500,
    type: 'expense',
    category: 'Needs',
  },
  {
    id: '3',
    date: subDays(new Date(), 3).toISOString(),
    description: 'Groceries from Whole Foods',
    amount: 250,
    type: 'expense',
    category: 'Needs',
  },
  {
    id: '4',
    date: subDays(new Date(), 4).toISOString(),
    description: 'Dinner with friends',
    amount: 120,
    type: 'expense',
    category: 'Wants',
  },
  {
    id: '5',
    date: subDays(new Date(), 5).toISOString(),
    description: 'Netflix Subscription',
    amount: 15.99,
    type: 'expense',
    category: 'Wants',
  },
  {
    id: '6',
    date: subDays(new Date(), 6).toISOString(),
    description: 'Electricity Bill',
    amount: 75.5,
    type: 'expense',
    category: 'Needs',
  },
  {
    id: '7',
    date: subDays(new Date(), 7).toISOString(),
    description: 'Stock Investment',
    amount: 500,
    type: 'expense',
    category: 'Savings',
  },
  {
    id: '8',
    date: subDays(new Date(), 8).toISOString(),
    description: 'New pair of shoes',
    amount: 180,
    type: 'expense',
    category: 'Wants',
  },
  {
    id: '9',
    date: subDays(new Date(), 10).toISOString(),
    description: 'Gas for car',
    amount: 60,
    type: 'expense',
    category: 'Needs',
  },
  {
    id: '10',
    date: subDays(new Date(), 12).toISOString(),
    description: 'Concert Tickets',
    amount: 220,
    type: 'expense',
    category: 'Wants',
  },
];
